name: "Wait For deployments"
description: "Waits for all deployments to complete before continuing."
branding:
  icon: "server"
  color: "blue"
inputs:
  github_token:
    description: "GitHub access token."
  check_interval:
    description: "Seconds to wait between deployment checks."
    default: "30"
    required: false
  max_timeout:
    description: "Max seconds to wait for the deploys to finish."
    default: "600"
    required: false
outputs:
  deployments:
    description: "Array containing the deployment environments and URLs"
runs:
  using: "node12"
  main: "index.js"
