name: "Wait For deployments"
description: "Waits for all deployments to complete before continuing."
branding:
  icon: "server"
  color: "blue"
inputs:
  github_token:
    description: "GitHub access token."
  environment_filter:
    description: "Regular expression to filter which environments we are waiting for."
    required: false
  initial_delay:
    description: "Time to wait before starting checks."
    default: "0s"
    required: false
  check_interval:
    description: "Time to wait between deployment checks."
    default: "30s"
    required: false
  max_timeout:
    description: "Time to wait for the deploys to finish."
    default: "20m"
    required: false
outputs:
  deployments:
    description: "Array containing the deployment environments and URLs."
runs:
  using: "node12"
  main: "index.js"
